language: shell
jobs:
    include:
        -
            os: windows
            script:
            ##- ls C:/tools/msys64/mingw64/bin
            - C:/tools/msys64/mingw64/bin/make --version
            - make --version
            - echo $PATH
            ##- ls /bin /usr/bin
            - pacman -Ql patch.exe
            - bsdtar --version
            - where bsdtar.exe
            - where bash
            - where patch
before_script:
    - 'cd $TRAVIS_BUILD_DIR'
before_install:
- |-
    case $TRAVIS_OS_NAME in
        windows)
          [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
          choco upgrade --no-progress -y msys2
          export msys2='cmd //C RefreshEnv.cmd '
          export msys2+='& set MSYS=winsymlinks:nativestrict '
          export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
          export shell="$msys2 -mingw64 -full-path -here -c \$\* --"
          export msys2+=" -msys2 -c \$\* --"
          $msys2 pacman --sync --noconfirm --needed \
                autoconf \
                automake \
                mingw-w64-x86_64-libtool \
                mingw-w64-x86_64-toolchain \
                bsdtar wget unzip patch bison
          taskkill //IM gpg-agent.exe //F
          export PATH=/C/tools/msys64/mingw64/bin:$PATH
          export MAKE=mingw32-make
          cp C:/tools/msys64/mingw64/bin/mingw32-make C:/tools/msys64/mingw64/bin/make
          ;;
      esac
before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac
cache:
    directories:
        - $HOME/AppData/Local/Temp/chocolatey
        - /C/tools/msys64
notifications:
    email: false
